name: dxvk-nvapi-mingw

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - public/dxvk-nvapi-mingw/.SRCINFO

jobs:
  repository:
    strategy:
      matrix:
        repository: [personal]
    uses: ./.github/workflows/job_pkgrepo.yml
    with:
      pkgdir: public/dxvk-nvapi-mingw
      repository: ${{ matrix.repository }}
