
name: dxvk-mingw-clang-git

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Repository action"
        required: true
        type: choice
        default: 'build'
        options:
        - 'build'
        - 'remove'
        - 'skip'
  schedule:
        - cron:  '0 0 */3 * *'
  push:
    branches:
     - master
    paths:
     - local/dxvk-mingw-clang-git/.SRCINFO
jobs:
  repository:
    strategy:
      matrix:
        repository: [personal]
    uses: ./.github/workflows/job_pkgrepo.yml
    with:
      pkgdir: local/dxvk-mingw-clang-git
      repository: ${{ matrix.repository }}
      action: ${{ inputs.action != '' && inputs.action || 'build' }}
