on:
  push:
    branch: master

jobs:
  build-pacman-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pacman-repo-builder/action@0.0.0-rc.64
        with:
          command: build-pacman-repo build
