on:
  push:
    branch: master

jobs:
  build-pacman-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pacman-repo-builder/action@<TAG>
        with:
          command: build-pacman-repo build
