name: CI

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate package
        uses: hapakaien/archlinux-package-action@v2
        with:
          path: package
          flags: '-si --noconfirm'
          namcap: false
