name: modprobed-db

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - aur/modprobed-db/.SRCINFO

jobs:
  repository:
    strategy:
      matrix:
        repository: [personal]
    uses: ./.github/workflows/job_pkgrepo.yml
    with:
      pkgdir: aur/modprobed-db
      repository: ${{ matrix.repository }}
