name: pacman-static

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - aur/pacman-static/.SRCINFO

jobs:
  repository:
    strategy:
      matrix:
        repository: [personal]
    uses: ./.github/workflows/job_pkgrepo.yml
    with:
      pkgdir: aur/pacman-static
      repository: ${{ matrix.repository }}
