name: proton-experimental

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - public/proton-experimental/.SRCINFO

jobs:
  repository:
    strategy:
      matrix:
        repository: [personal]
    uses: ./.github/workflows/job_pkgrepo.yml
    with:
      pkgdir: public/proton-experimental
      repository: ${{ matrix.repository }}
      multilib: true
