name: protonmail-bridge

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - public/protonmail-bridge/.SRCINFO

jobs:
  repository:
    strategy:
      matrix:
        repository: [personal]
    uses: ./.github/workflows/job_pkgrepo.yml
    with:
      pkgdir: public/protonmail-bridge
      repository: ${{ matrix.repository }}
