
name: protonmail-desktop

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - local/protonmail-desktop/.SRCINFO

jobs:
  repository:
    strategy:
      matrix:
        repository: [public]
  repository:
    strategy:
      matrix:
        repository: [personal]
    uses: ./.github/workflows/job_pkgrepo.yml
    with:
      pkgdir: local/protonmail-desktop
      repository: ${{ matrix.repository }}
