name: scx-scheds-git

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - public/scx-scheds-git/.SRCINFO
  schedule:
        - cron:  '0 0 */3 * *'

jobs:
  repository:
    strategy:
      matrix:
        repository: [personal]
    uses: ./.github/workflows/job_pkgrepo.yml
    with:
      pkgdir: public/scx-scheds-git
      repository: ${{ matrix.repository }}
