name: scx-scheds-git-bpfland

on:
  workflow_dispatch:
   inputs:
    action:
        description: "Repository action"
        required: true
        type: choice
        default: 'build'
        options:
        - 'build'
        - 'remove'
        - 'skip'
  push:
    branches:
     - master
    paths:
     - public/scx-scheds-git-bpfland/.SRCINFO

jobs:
  repository:
    strategy:
      matrix:
        repository: [personal]
    uses: ./.github-bpfland/workflows/job_pkgrepo.yml
    with:
      pkgdir: public/scx-scheds-git-bpfland
      repository: ${{ matrix.repository }}
      action: ${{ inputs.action != '' && inputs.action || 'build' }}
