name: vkd3d-proton-mingw-git

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 6 */3 * *'
  push:
    branches:
     - master
    paths:
     - /vkd3d-proton-mingw-git/.SRCINFO

jobs:
  repository:
    strategy:
      matrix:
        repository: [, personal]
    uses: ./.github/workflows/job_pkgrepo.yml
    with:
      pkgdir: /vkd3d-proton-mingw-git
      repository: ${{ matrix.repository }}
