name: vkd3d-proton-mingw

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - public/vkd3d-proton-mingw/.SRCINFO

jobs:
  repository:
    strategy:
      matrix:
        repository: [public, personal]
    uses: ./.github/workflows/job_pkgrepo.yml
    with:
      pkgdir: public/vkd3d-proton-mingw
      repository: ${{ matrix.repository }}
      usegcc: true
