name: wine-tkg

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - local/wine-tkg/.SRCINFO

jobs:
  repository:
    strategy:
      matrix:
        repository: [personal]
    uses: ./.github/workflows/job_pkgrepo.yml
    with:
      pkgdir: local/wine-tkg
      repository: ${{ matrix.repository }}
      multilib: true
      usegcc: true
