
name: wine-cachyos

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Repository action"
        required: true
        type: choice
        default: 'build'
        options:
        - 'build'
        - 'remove'
        - 'skip'
  push:
    branches:
     - master
    paths:
     - local/wine-cachyos/.SRCINFO

jobs:
  repository:
    strategy:
      matrix:
        include:
          - repository: personal
            usegcc: true
    uses: ./.github/workflows/job_pkgrepo.yml
    with:
      pkgdir: local/wine-cachyos
      repository: ${{ matrix.repository }}
      action: ${{ inputs.action != '' && inputs.action || 'build' }}
      multilib: true
      usegcc: ${{ matrix.usegcc}}
