name: wine-ntsync

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - multilib/wine-ntsync/.SRCINFO

jobs:
  repository:
    strategy:
      matrix:
        include:
          - repository: personal
            pkgbuild: PKGBUILD
            multilib: true
    uses: ./.github/workflows/job_pkgrepo.yml
    with:
      pkgdir: multilib/wine-ntsync
      repository: ${{ matrix.repository }}
      pkgbuild: ${{ matrix.pkgbuild }}
      multilib: ${{ matrix.multilib }}
