
name: wine-ge-custom-opt

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Repository action"
        required: true
        type: choice
        default: 'build'
        options:
        - 'build'
        - 'remove'
        - 'skip'
  push:
    branches:
     - master
    paths:
     - public/wine-ge-custom-opt/.SRCINFO
     - local/wine-ge-custom-opt/.SRCINFO

jobs:
  repository:
    strategy:
      matrix:
        include:
          - repository: public
            pkgdir: public/wine-ge-custom-opt
            pkgbuild: PKGBUILD
            multilib: true
          - repository: personal
            pkgdir: local/wine-ge-custom-opt
            pkgbuild: PKGBUILD
            multilib: true
    uses: ./.github/workflows/job_pkgrepo.yml
    with:
      pkgdir: ${{ matrix.pkgdir }}
      repository: ${{ matrix.repository }}
      action: ${{ inputs.action != '' && inputs.action || 'build' }}
      pkgbuild: ${{ matrix.pkgbuild }}
      multilib: ${{ matrix.multilib }}
